import type { Metadata } from "next";
import Link from "next/link";
import { LEGAL_VERSION } from "../../lib/legal";

export const metadata: Metadata = { title: "Privacy Notice" };

export default function PrivacyPage() {
  return <article className="mx-auto max-w-3xl space-y-8 py-10 text-sm leading-7 text-zinc-700 dark:text-zinc-300">
    <header><p className="text-xs font-bold uppercase tracking-widest text-[#2E7CF6]">Effective {LEGAL_VERSION}</p><h1 className="mt-2 font-display text-4xl font-black text-zinc-950 dark:text-white">TICKR Privacy Notice</h1><p className="mt-3">This notice explains how the TICKR team handles information when you use the app. It is separate from the <Link href="/terms" className="text-[#2E7CF6] underline">Terms of Use</Link>.</p></header>
    <section><h2 className="text-xl font-bold text-zinc-950 dark:text-white">Information we handle</h2><p>To run your account and game activity, TICKR handles your sign in identifier, linked wallet address, username, selected team, optional bio, and market actions. Privy provides sign in and wallet services. Market transactions are recorded on a public blockchain. We also store a signed browser cookie recording that you acknowledged this version of the legal documents; local browser storage keeps your theme and watchlist preferences.</p></section>
    <section><h2 className="text-xl font-bold text-zinc-950 dark:text-white">Why we use it</h2><p>We use this information to authenticate you, display your profile and game activity, calculate your private rank and performance, operate claims and market features, remember your preferences, prevent abuse, and respond to support requests. Your legal acknowledgement is used to decide whether to allow an authenticated session to continue.</p></section>
    <section><h2 className="text-xl font-bold text-zinc-950 dark:text-white">Who can see it</h2><p>Wallet addresses and blockchain transactions are public. Your username, bio, selected team, and public market activity may appear on public profile pages. Your private financial analytics and player rank are shown only to your authenticated account. Service providers used to host the app, store profile data, and provide authentication or price data may process information needed to operate those services.</p></section>
    <section><h2 className="text-xl font-bold text-zinc-950 dark:text-white">Storage and retention</h2><p>We keep profile and indexed game data while needed to operate TICKR and meet applicable obligations. The legal acknowledgement cookie lasts up to one year, or until the documents change. You can remove local preferences using your browser settings. Public blockchain records cannot be deleted by TICKR.</p></section>
    <section><h2 className="text-xl font-bold text-zinc-950 dark:text-white">Your choices and requests</h2><p>You can leave the optional bio blank, remove watched markets, decline the legal acknowledgement and sign out, or stop using the app. To request access, correction, or deletion of information TICKR controls, contact us. We will assess requests under applicable law; we cannot change public blockchain history or information held by independent providers.</p></section>
    <section><h2 className="text-xl font-bold text-zinc-950 dark:text-white">Contact and updates</h2><p>Contact the TICKR team at <a href="https://x.com/tickrtop" target="_blank" rel="noopener noreferrer" className="text-[#2E7CF6] underline">@tickrtop on X</a> about privacy requests. We may update this notice and will ask you to acknowledge a materially changed version before continuing.</p></section>
  </article>;
}
