"use client";

import Link from "next/link";
import { Bell, BellRing, ArrowRight } from "lucide-react";
import { useMarkets } from "../../lib/query/useMarkets";
import { useWatchlist } from "../../lib/watchlist";
import { TEMPLATES, TEMPLATE_NAMES } from "../../lib/marketFactory";

export default function WatchlistPage() {
  const { wallet, entries, notices, toggle, setAlert } = useWatchlist();
  const { markets } = useMarkets();
  const canNotify = typeof Notification !== "undefined";
  return <div className="mx-auto max-w-4xl pb-16">
    <div className="rounded-[2rem] bg-gradient-to-br from-[#0d224b] via-[#174896] to-[#2E7CF6] p-7 text-white sm:p-10"><BellRing className="h-7 w-7" /><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-white/65">Your watchlist</p><h1 className="mt-2 font-display text-4xl font-black">Follow the markets that matter.</h1><p className="mt-3 max-w-xl text-sm text-white/75">Get in-app updates when a watched market approaches its target, closes soon, or settles.</p></div>
    {!wallet ? <p className="mt-8 rounded-2xl border border-black/10 p-6 text-sm dark:border-white/10">Sign in to save a watchlist for your wallet.</p> : <>
      <div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-black/10 p-4 dark:border-white/10"><div><p className="font-bold">Browser notifications</p><p className="text-xs text-zinc-500">Optional. Alerts are checked while TICKR is open; your in-app updates remain here.</p></div><button type="button" disabled={!canNotify || Notification.permission === "granted"} onClick={() => void Notification.requestPermission()} className="rounded-xl bg-[#2E7CF6] px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{canNotify && Notification.permission === "granted" ? "Enabled" : "Enable notifications"}</button></div>
      <section className="mt-9"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-black">Watched markets</h2><Link href="/markets" className="text-xs font-bold text-[#2E7CF6]">Explore markets <ArrowRight className="inline h-3 w-3" /></Link></div>{entries.length ? <div className="mt-4 space-y-3">{entries.map((entry) => { const market = markets?.find((m) => m.id === Number(entry.marketId)); return <div key={entry.marketId} className="rounded-2xl border border-black/10 bg-white p-5 dark:border-white/10 dark:bg-[#101821]"><div className="flex flex-wrap items-start justify-between gap-3"><Link href={`/markets/${entry.marketId}`} className="font-bold hover:text-[#2E7CF6]">{market ? TEMPLATE_NAMES[market.templateId] : "Market"} #{entry.marketId}<span className="ml-2 text-xs font-normal text-zinc-500">{market?.state === 0 ? "Open" : "Settled"}</span></Link><button onClick={() => toggle(entry.marketId)} className="text-xs font-bold text-zinc-500 hover:text-red-500">Remove</button></div><div className="mt-4 flex flex-wrap gap-4 text-xs">{(["closing", "settled", ...(market?.templateId === TEMPLATES.TARGET ? ["nearTarget"] : [])] as Array<"closing" | "settled" | "nearTarget">).map((field) => <label key={field} className="flex cursor-pointer items-center gap-2"><input type="checkbox" checked={entry[field]} onChange={(e) => setAlert(entry.marketId, field, e.target.checked)} className="accent-[#2E7CF6]" />{field === "nearTarget" ? "Within 1% of target" : field === "closing" ? "Closing within 1 hour" : "Result posted"}</label>)}</div></div>; })}</div> : <div className="mt-4 rounded-2xl border border-dashed border-black/15 p-8 text-center text-sm text-zinc-500 dark:border-white/15"><Bell className="mx-auto mb-3 h-6 w-6" />Watch a market to see it here.</div>}</section>
      <section className="mt-10"><h2 className="font-display text-xl font-black">Updates</h2>{notices.length ? <div className="mt-4 divide-y divide-black/10 rounded-2xl border border-black/10 dark:divide-white/10 dark:border-white/10">{notices.map((notice) => <Link key={notice.key} href={`/markets/${notice.marketId}`} className="flex items-center justify-between gap-4 p-4 text-sm hover:bg-black/[.03] dark:hover:bg-white/[.03]"><span>{notice.message}</span><time className="shrink-0 text-xs text-zinc-500">{new Date(notice.at).toLocaleString()}</time></Link>)}</div> : <p className="mt-3 text-sm text-zinc-500">Updates will appear here when a watched market reaches an alert condition.</p>}</section>
    </>}
  </div>;
}
